ibrokervn/DexuatGD/urls.py
from __future__ import unicode_literals
from mezzanine.conf import settings

_slash = "/" if settings.APPEND_SLASH else ""


from django.conf.urls import url
from DexuatGD import views


app_name='DexuatGD'
urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.stock_detail,
        name='phantichcophieu'),
    url(r'^tonghopthongtin/', views.Tonghopthongtin, name='tonghopthongtin'),
    url(r'^import_Doanhnghiep/', views.import_Stock_basic_info , name='import'),
    url("^tag/(?P<tag>.*)%s$" % _slash,
        views.Nhandinh_list, name="NhandinhTT_DexuatGD_list_tag"),
    url("^category/(?P<category>.*)%s$" % _slash,
        views.Nhandinh_list, name="NhandinhTT_DexuatGD_list_category"),
    url("^author/(?P<username>.*)%s$" % _slash,
        views.Nhandinh_list, name="NhandinhTT_DexuatGD_list_author"),
    url("^archive/(?P<year>\d{4})/(?P<month>\d{1,2})%s$" % _slash,
        views.Nhandinh_list, name="NhandinhTT_DexuatGD_list_month"),
    url("^archive/(?P<year>\d{4})%s$" % _slash,
        views.Nhandinh_list, name="NhandinhTT_DexuatGD_list_year"),
    url("^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/"
        "(?P<slug>.*)%s$" % _slash,
        views.Nhandinh_detail, name="Nhandinh_detail_day"),
    url("^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>.*)%s$" % _slash,
        views.Nhandinh_detail, name="Nhandinh_detail_month"),
    url("^(?P<year>\d{4})/(?P<slug>.*)%s$" % _slash,
        views.Nhandinh_detail, name="Nhandinh_detail_year"),
    url("^nhandinhmoinhat%s$" % _slash, views.Nhandinh_detail_moinhat, name='newest'),
    url("^(?P<slug>.*)%s$" % _slash, views.Nhandinh_detail, name='daily'),
    url("^$", views.Nhandinh_list, name="NhandinhTT_DexuatGD_list"),
      ]

ibrokervn/GDNN/urls.py
from django.conf.urls import url

from django.conf.urls.i18n import i18n_patterns
from GDNN import views

app_name='GDNN'
urlpatterns = i18n_patterns (
    url(r'import_GDNN',views.import_GDNN, name='import_gdnn'),
    url(r'$',views.TKgdnn, name='gdnn'),

)

ibrokervn/ibrokervn/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin


from mezzanine.core.views import direct_to_template


admin.autodiscover()


urlpatterns = i18n_patterns(

    url("^admin/", include(admin.site.urls)),
    url(r'^toidautu/giaodichNN/', include('GDNN.urls',namespace='giaodichNN',app_name='GDNN')),
    url(r'^toidautu/thongtinvimo/', include('Vimo.urls',namespace='thongtinvimo',app_name='Vimo')),
    url(r'^toidautu/', include('DexuatGD.urls',namespace='nhandinhthitruong',app_name='DexuatGD')),
    url(r'^auth/',include('social_django.urls', namespace='social')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth'))
               )
urlpatterns += [

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    url("^", include("mezzanine.urls")),


]
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

ibrokervn/mezzanine/project_template/project_name/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

# Uncomment to use blog as home page. See also urlpatterns section below.
# from mezzanine.blog import views as blog_views

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", blog_views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

ibrokervn/toidautu/urls.py
from django.conf.urls import url
from Main import views


app_name='Main'
urlpatterns = [
    url(r'chienluocgiaodich$', views.Trading_strategy , name='index'),
      ]

ibrokervn/toidautu/models.py
from django.db import models

# Create your models here.

ibrokervn/toidautu/templates/pages/toidautu/NhandinhTT_DexuatGD_list.html
{% extends "base_toidautu.html" %}
{% load toidautu_tags %}
{% load i18n mezzanine_tags keyword_tags disqus_tags %}
{% load staticfiles %}
{% block meta_title %}{{ page.meta_title }}{% endblock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}
{% block stylesheets %}
   {{ block.super }}


{% endblock stylesheets %}
{% block content %}
{% block main %}
<!-- Content Header (Page header) -->
<section class="content-header">
{% block title %}TỔNG HỢP NHẬN ĐỊNH THỊ TRƯỜNG{% endblock title %}
</section>	
	<section id="blog" class="content">

	<div class="row">		
	<div class="col-md-9">
	<div class="blog">
			{% if tag or category or year or month or author %}
    	{% block Nhandinh_posts_list_filterinfo %}
    		<p>
    		{% if tag %}
    		    {% trans "Đang xem bài trong tagged" %}<strong style="text-transform: uppercase;"> {{ tag }} </		strong>
    		{% else %}{% if category %}
    		    {% trans "Đang xem bài trong mục" %}<strong style="text-transform: uppercase;">  {{ category }}  </		strong>
    		{% else %}{% if year or month %}
    		    {% trans "đang xem bài từ tháng" %} {% if month %}{{ month }}, {% endif %}
    		   <strong style="text-transform: uppercase;">  {{ year }}  </strong>
    		{% else %}{% if author %}
    		    {% trans "Đang xem bài được viết bởi" %} <strong style="text-transform: uppercase;">  
    		    {{ author.get_full_name|default:author.username }}  </strong>
    		{% endif %}{% endif %}{% endif %}{% endif %}
    		{% endblock %}
			    </p>
			{% else %}
			    {% if page %}
			    {% block Nhandinh_posts_list_pagecontent %}
			    {% if page.get_content_model.content %}
			        {% editable page.get_content_model.content %}
			        {{ page.get_content_model.content|richtext_filters|safe }}
			        {% endeditable %}
			    {% endif %}
			    {% endblock %}
			    {% endif %}
			{% endif %}		
				{% for Nhandinh_posts in Nhandinh_posts.object_list %}
				 <div class="blog-item">
					 {% if settings.BLOG_USE_FEATURED_IMAGE and Nhandinh_posts.featured_image %}
						{% block Nhandinh_posts_list_post_featured_image %}
						<a href="{{ Nhandinh_posts.get_absolute_url }}">
							<img width="100%" class="img-responsive img-blog" src="{{ MEDIA_URL }}{{ 			Nhandinh_posts.featured_image }}">
						</a>
						{% endblock %}
						{% endif %}
					<div class="blog-content">			
				{% block Nhandinh_posts_list_post_title %}	
					{% editable Nhandinh_posts.title %}
					<a href="{{ Nhandinh_posts.get_absolute_url }}"><h3>{{ Nhandinh_posts.title }}</h3></a>
					{% endeditable %}
				{% endblock %}
			{% block Nhandinh_posts_list_post_metainfo %}
			{% editable Nhandinh_posts.publish_date %}
                   <div class="entry-meta">
                                <span><i class="icon-user"></i> {% with Nhandinh_posts.user as author %}
								<a href="{% url "nhandinhthitruong:NhandinhTT_DexuatGD_list_author" author %}">{{ author.get_full_name|default:author.username }}</a>
								{% endwith %}
								</span>
								<span><i class="icon-folder-close"></i>
                                {% with Nhandinh_posts.categories.all as categories %}
								{% if categories %}
								{% trans "chuyên mục" %}
								{% for category in categories %}
								<a href="{% url "nhandinhthitruong:NhandinhTT_DexuatGD_list_category" category.slug %}"><strong style="text-transform: uppercase;">
								"{{ category }}"	</strong></a>{% if not forloop.last %}, {% endif %}
								{% endfor %}
								{% endif %}
								{% endwith %}                                
                                </span>
                                <span><i class="icon-calendar"></i> {% blocktrans with sometime=Nhandinh_posts.publish_date|date:"d/m/y H:i a " %}{{ sometime }} {% endblocktrans %}</span>
                                <span><i class="icon-comment"></i> 
                                {% if Nhandinh_posts.allow_comments %}							
									{% if settings.COMMENTS_DISQUS_SHORTNAME %}
									<a href="{{ Nhandinh_posts.get_absolute_url }}#disqus_thread"
										data-disqus-identifier="{% disqus_id_for Nhandinh_posts %}">
										{% trans "Comments" %}
									</a>
									{% else %}
									<a href="{{ Nhandinh_posts.get_absolute_url }}#comments">
										{% blocktrans count comments_count=Nhandinh_posts.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} nhận định khác{% endblocktrans %}
									</a>
									{% endif %}
									{% endif %}														
                                </span>
                            </div>
{% endeditable %}
{% endblock %}
{% block Nhandinh_posts_list_post_content %}
{% editable Nhandinh_posts.content %}
{{ Nhandinh_posts.description_from_content|safe }}
{% endeditable %}
{% endblock %}
 <a href="{{ Nhandinh_posts.get_absolute_url }}" class="btn btn-default">{% trans "chi tiết..." %} <i class="icon-angle-right"> </i></a>
{% block Nhandinh_posts_list_post_links %}
{% keywords_for Nhandinh_posts as tags %}
    {% if tags %}
<div class="tags">
  <i class="icon-tags"></i> {% trans "Tags" %}:
    {% spaceless %}
    {% for tag in tags %} 
  <a href="{% url "nhandinhthitruong:NhandinhTT_DexuatGD_list_tag" tag.slug %}" class="btn btn-xs btn-primary">{{ tag }}</a> &nbsp;
  {% endfor %}
    {% endspaceless %}
</div>
{% endif %}
</div>
</div>
{% endblock %}
{% endfor %}
</div>
<!-- Endblog content -->

</div>
	    <!-- Right panel -->
		{% block right_panel %}
		<div class="col-md-3">

          <!-- Profile Image -->
          <div class="box box-primary">
            <div class="box-body box-profile"> 



		{% include "filter_toidautu.html" %} 

		</div>
		</div>
		</div>
		{% endblock %}

{% pagination_for Nhandinh_postss %}
{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_counts.html" %}
{% endif %}
</div>

</section>
{% endblock %}
</section>
<!-- /.content -->         
{% endblock content %}
{% block javascripts %}
  {{ block.super}}
<!-- REQUIRED JS SCRIPTS -->
{% endblock javascripts %}

ibrokervn/toidautu/templates/pages/toidautu/capnhatthongtintt.html
{% extends "base_toidautu.html" %}
{% load toidautu_tags %}
{% load staticfiles %}
{% block title %} CHIẾN LƯỢC GIAO DỊCH {% endblock title %}


{% block stylesheets %}

  {{ block.super }}
  <script src="{% static "js/gauge.js" %}"></script>
  

  
  
{% endblock stylesheets %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Tổng quan Thị Trường & Chiến lược GD
    <small>cập nhật 23/12/18</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="chienluocgiaodich"><i class="fa fa-home"></i> chienluocGD</a></li>
    <li class="active">Here</li>
  </ol>
</section>

 <!-- Main content -->
    <section class="content">
      <div class="row">  <!-- Để co margin trái phải lại -15px -->
      <div class="row">  <!-- Để co margin trái phải lại -15px -->
      <!-- CỘT TRÁI -->      
        <div class="col-md-6" >
          {%Vimosimple%}

          <div class="box box-info box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">ĐÁNH GIÁ VN INDEX</h3>
            </div>
            <!-- /.box-header -->
              <div class="box-body no-padding">
  
                <!-- gauge.js -->
                    
                <div style="height: 300px" >
              
                  <div>
  
                     <div id="preview-textfield"></div>
  
                    <canvas id="gauge" ></canvas>
                    <div id="cmtTT" >MẠNH</div>
                  </div>
                </div>
              </div>


              <script>
                  var opts1 = {
                    angle: 0.08, // The span of the gauge arc
                    lineWidth: 0.44, // The line thickness
                      radiusScale: 1, // Relative radius
                    pointer: {
                      length: 0.6, // // Relative to gauge radius
                      strokeWidth: 0.035, // The thickness
                      color: '#000000' // Fill color
                    },
                    limitMax: false,     // If false, max value increases automatically if value > maxValue
                    limitMin: false,     // If true, the min value of the gauge will be fixed
                    colorStart: '#6FADCF',   // Colors
                    colorStop: '#23DA2F',    // just experiment with them
                    strokeColor: '#F2301B',  // to see which ones work best for you
                    generateGradient: true,
                    highDpiSupport: true,     // High resolution support
                    // renderTicks is Optional
                    renderTicks: {
                      divisions: 8,
                      divWidth: 1.2,
                      divLength: 0.59,
                      divColor: '#333333',
                      subDivisions: 4,
                      subLength: 0.26,
                      subWidth: 1,
                      subColor: '#666666'
                    }
                  };
                  var target = document.getElementById('gauge'); // your canvas element
                  var gauge = new Gauge(target).setOptions(opts1); // create sexy gauge!
                  gauge.setTextField(document.getElementById("preview-textfield"));
                  gauge.maxValue = 100; // set max gauge value
                  gauge.setMinValue(0);  // Prefer setter over gauge.minValue = 0
                  gauge.animationSpeed = 32; // set animation speed (32 is default value)
                  gauge.set(75); // set actual value

              </script>
            

            <table class="table">
              <tr>
                <th style="width: 100px; text-align:center; ">Ngành dẫn dắt TT</th>
                <th>Mức độ</th>
                <th >CP nổi bật</th>
              </tr>
              <tr>
                <td><span class="badge bg-red">Ngân hàng</span></td>
                <td>
                  <div class="progress progress-xs">
                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                  </div>
                </td>
                <td>VCB BID TCB</td>
              </tr>
              <tr>
                <td><span class="badge bg-yellow">BĐS</span></td>
                <td>
                  <div class="progress progress-xs">
                    <div class="progress-bar progress-bar-yellow" style="width: 70%"></div>
                  </div>
                </td>
                <td>NVL VHM KDH</td>
              </tr>
              <tr>
                <td><span class="badge bg-light-blue">Dệt may</span></td>
                <td>
                  <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar progress-bar-primary" style="width: 30%"></div>
                  </div>
                </td>
                <td>TCM STK</td>
              </tr>
              <tr>
                <td><span class="badge bg-green">Bán lẻ</span></td>
                <td>
                  <div class="progress progress-xs progress-striped active">
                    <div class="progress-bar progress-bar-green" style="width: 90%"></div>
                  </div>
                </td>
                <td>VNM PNJ</td>
              </tr>
            </table>

          </div>
            <!-- /.box-body -->

            <div class="box box-primary box-solid">
              <div class="box-header with-border" style="height: 50px">
                <h3 class="box-title">CP ĐẦU TƯ NGẮN HẠN </h3>
              </div>
              <!-- /.box-header -->
              <div class="box-body no-padding">
                <table class="table table-bordered">
                  <tr ">
                    <th style="width: 10px; text-align:center;">Stock</th>
                    <th style="width: 80px; ">Trade</th>
                    <th style="width: 80px; text-align:center;">Giá KN</th>
                    <th style="width: 80px; text-align:center;">Cập nhật</th>
                    <th style="width: 80px; ">Lời/Lỗ</th>
                    <th style="text-align:center;">Độ mạnh</th>
                  </tr>
                  <tr>
                    <td>AAA</td>
                    <td><span class="badge bg-yellow">Mua mới</span></td>
                    <td style="text-align:center;"> 22  </td>
                    <td style="text-align:center;"> 25  </td>
                    <td><i class="fa fa-arrow-up bg-green"></i> 15%  </td>
                    <td style="text-align:center;">
                      <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-green" style="width: 60%"></div>
                      </div>
                    </td>                   
                    <td style="text-align:center;"><span class="badge bg-red">55%</span></td>
                  </tr>
                  <tr>
                    <td>ABC</td>
                    <td><span class="badge bg-light-blue">Bán bớt</span></td>
                    <td style="text-align:center;"> 22 </td>
                    <td style="text-align:center;"> 25 </td>
                    <td><i class="fa fa-arrow-down bg-red"></i> -10% </td>
                    <td style="text-align:center;">
                      <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-green" style="width: 90%"></div>
                      </div>
                    </td>    
                    <td style="text-align:center;">    
                      <span class="badge bg-yellow">70%</span>
                    </td>
                  </tr>
                  <tr>
                    <td>STK</td>
                    <td style="text-align:center;"><span class="badge bg-green">Mua thêm</span></td>
                    <td style="text-align:center;"> 30 </td>
                    <td style="text-align:center;"> 37 </td>
                    <td><i class="fa fa-arrow-up bg-green"></i> 20% </td>
                    <td style="text-align:center;">
                      <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-green" style="width: 20%"></div>
                      </div>
                    </td> 
                    <td style="text-align:center;"><span class="badge bg-light-blue">30%</span></td>
                  </tr>
                  <tr>
                    <td style="text-align:center;">HCM</td>
                    <td><span class="badge bg-red">Cắt lỗ</span></td>
                    <td style="text-align:center;">  </td>
                    <td style="text-align:center;">  </td>
                    <td><i class="fa fa-arrow-up bg-green"></i></td>
                    <td style="text-align:center;">
                      <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-green" style="width: 50%"></div>
                      </div>
                    </td> 
                    <td style="text-align:center;"><span class="badge bg-green">90%</span></td>
                  </tr>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
            <!-- /.box -->
         
         

        </div>
          <!-- /.col -->
              
     
            
         <!-- CỘT PHẢI -->       
        <div class="col-md-6" >
          
           <!-- TKgdNN -->

          {%TKgdnn%}
      
       


          <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">TT Thế giới</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="height: 560px">
            <!-- TradingView Widget BEGIN -->
            <div class="tradingview-widget-container">
              <div class="tradingview-widget-container__widget"></div>
              <div class="tradingview-widget-copyright"><a href="https://vn.tradingview.com/markets/indices/" rel="noopener" target="_blank"><span class="blue-text">Các chỉ số</span></a>, <a href="https://vn.tradingview.com/markets/futures/" rel="noopener" target="_blank"><span class="blue-text">Hàng hóa</span></a> <span class="blue-text">và</span> <a href="https://vn.tradingview.com/markets/currencies/" rel="noopener" target="_blank"><span class="blue-text">Ngoại hối</span></a> bởi TradingView</div>
              <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js" async>
              {
              "showChart": true,
              "locale": "vi_VN",
              "width": "100%",
              "height": "100%",
              "largeChartUrl": "",
              "plotLineColorGrowing": "rgba(60, 188, 152, 1)",
              "plotLineColorFalling": "rgba(255, 74, 104, 1)",
              "gridLineColor": "rgba(233, 233, 234, 1)",
              "scaleFontColor": "rgba(214, 216, 224, 1)",
              "belowLineFillColorGrowing": "rgba(60, 188, 152, 0.05)",
              "belowLineFillColorFalling": "rgba(255, 74, 104, 0.05)",
              "symbolActiveColor": "rgba(242, 250, 254, 1)",
              "tabs": [
                {
                  "title": "Các chỉ số",
                  "symbols": [
                    {
                      "s": "INDEX:SPX",
                      "d": "S&P 500"
                    },
                    {
                      "s": "INDEX:IUXX",
                      "d": "Nasdaq 100"
                    },
                    {
                      "s": "INDEX:DOWI",
                      "d": "Dow 30"
                    },
                    {
                      "s": "INDEX:NKY",
                      "d": "Nikkei 225"
                    },
                    {
                      "s": "INDEX:DAX",
                      "d": "DAX Index"
                    },
                    {
                      "s": "OANDA:UK100GBP",
                      "d": "FTSE 100"
                    }
                  ],
                  "originalTitle": "Indices"
                },
                {
                  "title": "Hàng hóa",
                  "symbols": [
                    {
                      "s": "COMEX:GC1!",
                      "d": "Gold"
                    },
                    {
                      "s": "TVC:USOIL"
                    },
                    {
                      "s": "TVC:UKOIL"
                    },
                    {
                      "s": "NYMEX:KT1!"
                    }
                  ],
                  "originalTitle": "Commodities"
                },
                {
                  "title": "Ngoại hối",
                  "symbols": [
                    {
                      "s": "FX:EURUSD"
                    },
                    {
                      "s": "FX_IDC:USDVND"
                    },
                    {
                      "s": "FX:USDJPY"
                    },
                    {
                      "s": "FX_IDC:USDCNY"
                    },
                    {
                      "s": "FOREXCOM:USDRUB"
                    }
                  ],
                  "originalTitle": "Forex"
                }
              ]
            }
              </script>
            </div>



          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->


      </div>

   
 


  </section>
  <!-- /.content -->

          

{% endblock content %}

{% block javascripts %}
  {{ block.super}}
<!-- REQUIRED JS SCRIPTS -->


{% endblock javascripts %}